Fix README.md in G3tm31fy0uc4n
htcisme/G3tm31fy0uc4n pull request #4
Opened 2024-09-29 01:24 UTC by htcisme

2024-09-29 01:33 UTC, baoipc requested changes
Các quy tắc chưa kèm ví dụ -> gây khó hiểu. Chưa thực tế -> KHÔNG THỂ ÁP DỤNG
Cụ thể:
- Phần code: bao gồm các phần sẽ đặt tên theo rule, theo process
- phần data: những phần data raw, data đang xử lý, data đang dùng
Đặt tên branch: thường là tên task sẽ là tên branch

2024-09-29 01:37 UTC, baoipc commented
Cần có rule đặt tên các task -> lấy thành tên nhánh

2024-09-29 02:56 UTC, htcisme commented
@baoipc em chỉnh r á, a review lại giúp e với

2024-09-29 02:59 UTC, baoipc reviewed
trình bày lại, nhiều nội dung chung level thì xuống hàng cho dễ nhìn
tên task chưa clear và chi tiết --> chi tiết thêm : D

2024-09-29 03:13 UTC, htcisme commented
@baoipc Em có update thêm phần tạo ISSUE cho phần task để dễ quản lý rồi á, anh check lại giúp em nhé, mấy đoạn chung Level em có cách xuống luôn rồi

2024-09-29 03:16 UTC, baoipc reviewed
Quy tắc đặt tên repo [rule 1] - [rule 2] - ... - [rule n]
các quy tắc đặt tên chưa chi tiết, vì các rule nó đang trùng nhau chưa có nào là duy nhất : D

2024-09-29 03:43 UTC, htcisme commented
Em chỉnh lại r nhé, mà quy tắc đặt tên repo là gì v a, ko phải repo là chỉ có G3tm31fy0uc4n hả a

2024-09-29 05:10 UTC, baoipc commented
> Em chỉnh lại r nhé, mà quy tắc đặt tên repo là gì v a, ko phải repo là chỉ có G3tm31fy0uc4n hả a

đặt tên cái em push lên
Em suy nghĩ thêm về case anh nói nhé, nó chưa ổn đâu, fix thêm
:v cụ thể thì em phải image ra dể có nhiều case hơn về thực tế : D

2024-09-29 06:33 UTC, htcisme commented
Hmm cái commit e có add thêm message chi tiết rùi á
Còn mấy case a nói e đang liệt kê được một số thứ sau:
-------------------------
File dữ lieu
- Raw 
- Đã qua xử lý làm sạch
- Đã được embedding (Có thể có nhiều phiên bản) -> BERTBASE BERTSMALL

Tên mô hình/ embedding
- Có thể dính trùng lặp như Bert (nhiều phiên bản) -> Gộp vào file chung

Mô hình
- Có thể có nhiều layer ->   (Có thể gộp vào file chung và cho chọn số)

Task:
- Giao trên ISSUE, đặt tên theo dạng [Tên người nhận task]-[Label]-[Kiểu file cần thao tác]-[Đối tượng]
	Label về việc chỉnh sửa, them, xóa
---------------------------------------------------
Có một số thay đổi để có thể đồng bộ giữa các cách đặt tên và dễ kiếm hơn e có cập nhập

2024-09-30 05:11 UTC, baoipc reviewed
quy tắc đặt tên branch
quản lý task bằng branch, không dùng Issue !

2024-09-30 09:26 UTC, baoipc reviewed
vậy tên task thì sẽ do ai quy định?

2024-09-30 09:29 UTC, htcisme commented
> vậy tên task thì sẽ do ai quy định?

Thống kê ra các mô hình sẽ làm, dựa vào các tên mô hình và đặt. Đối với dữ liệu cũng v, sử dụng các cách lấy tên của model + data để đặt

2024-09-30 09:33 UTC, baoipc commented
quản lý tất cả task ở đâu

2024-09-30 12:01 UTC, baoipc commented
câu trả lời là dùng git project : D
nhưng mà có một vài lý do nên là sẽ không dùng repo này

2024-09-30 14:14 UTC, closed without merging